apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-cluster-role
rules:
  # Core Kubernetes resources
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes", "services", "endpoints", "configmaps", "secrets", "namespaces", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "watch"]

  # Apps API group
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

  # Extensions API group
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Storage API group
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

  # Prometheus Operator resources
  - apiGroups: ["monitoring.coreos.com"]
    resources: [
      "prometheuses", "servicemonitors", "alertmanagers", "thanosrulers", "scrapeconfigs",
      "prometheusagents", "probes", "prometheusrules", "podmonitors", "alertmanagerconfigs"
    ]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: [
      "prometheuses/status", "alertmanagers/status", "thanosrulers/status",
      "prometheusagents/status", "probes/status", "prometheusrules/status",
      "podmonitors/status", "alertmanagerconfigs/status"
    ]
    verbs: ["update", "patch"]

  # Grafana Operator resources
  - apiGroups: ["grafana.integreatly.org"]
    resources: [
      "grafanas", "grafanadashboards", "grafanadatasources", "grafanalibrarypanels",
      "grafanafolders", "grafanaalertrulegroups", "grafananotificationpolicies",
      "grafananotificationpolicyroutes", "grafananotificationtemplates",
      "grafanamutetimings", "grafanacontactpoints"
    ]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["grafana.integreatly.org"]
    resources: [
      "grafanas/status", "grafanadashboards/status", "grafanadatasources/status",
      "grafanalibrarypanels/status", "grafanafolders/status", "grafanaalertrulegroups/status",
      "grafananotificationpolicies/status", "grafananotificationpolicyroutes/status",
      "grafananotificationtemplates/status", "grafanamutetimings/status",
      "grafanacontactpoints/status"
    ]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: monitoring-service-account
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io
